name: relational_orm
description: A lightweight Active Record ORM for Dart and Flutter with relations, eager loading, polymorphic relationships, and support for custom database adapters.

version: 0.1.0

license: Apache-2.0

homepage: https://github.com/bbidpa/relational_orm
repository: https://github.com/bbidpa/relational_orm
issue_tracker: https://github.com/bbidpa/relational_orm/issues

topics:
  - orm
  - database
  - query-builder
  - flutter
  - sqlite

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  uuid: ^4.5.1
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^2.5.2
  json_serializable: ^6.9.5
  lints: ^6.0.0
  test: ^1.25.15